### ISSUE TITLE
Self-host authentication server

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#139]
## Problem that this feature solves

Currently our authentication is hosted on the [XR NL server](https://keyserver.extinctionrebellion.nl/). This is not very convenient because we can only access that server through one of our server administrators, who are not always very responsive. If we have an issue with the authentication server it usually takes too long until we can fix it.

## Feature description

Host the authentication server on the same Digital Ocean droplet as our Hasura server:

- [ ] get the test authentication server running on the same server as our dev Hasura
  server
- [ ] Connect the app (in dev mode) to the new dev authentication server
- [ ] Document instructions for how we can replicate this setup. This is important
  for deploying the authentication server for production

**Comment by SamLubbers** [comment]
@tomootes made the good suggestion that we should deploy this authentication server independently so that we can reuse it for other XR (NL) services.

**Comment by SamLubbers** [comment]
Here is already the `docker-compose` that we use for the current for the current authentication server. What's weird from this is that it also has a hasura engine and a postgres database not used by keycloack :thinking: 

```yml
version: "3.3"

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '~snip~'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  keycloak:
    restart: always
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "~snip~"
      DB_VENDOR: "postgres"
      DB_ADDR: "db-postgresql-ams3-49385-do-user-7256383-0.b.db.ondigitalocean.com"
      DB_DATABASE: "defaultdb"
      DB_PORT: 25060
      DB_USER: "doadmin"
      DB_PASSWORD: "~snip~"
      PROXY_ADDRESS_FORWARDING: "true"
    image: jboss/keycloak:11.0.3
    ports:
    - 8082:8080
volumes:
  db_data:
```

I'll setup a new server with this docker-compose, and the configuration currently stored in the database at the address `DB_ADDR`
